language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $UPLOAD_FILE
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
